name: Restart the camera if needed

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  schedule:
    # at every 30th minute from 7:30 to 21:30 (no DST = UTC+2)
    - cron: '30 5-19 * 4-10 *'
    # same thing during DST (UTC+1)
    - cron: '30 6-20 * 1-3,11-12 *'
  workflow_dispatch:

jobs:
  restart:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Restart the camera if needed
        env:
          CAMERA_URL: ${{ secrets.CAMERA_URL }}
          CAMERA_USERNAME: ${{ secrets.CAMERA_USERNAME }}
          CAMERA_PASSWORD: ${{ secrets.CAMERA_PASSWORD }}
        run: python online/restart_camera_if_needed.py
